import type { Metadata } from "next";
import { Inter, Red_Hat_Display } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";
const inter = Inter({
  variable: "--font-inter", // Custom CSS variable name
  subsets: ["latin"],
  weight: ["400", "600"], // Example: You can add weights you need
});

const redHatDisplay = Red_Hat_Display({
  variable: "--font-red-hat-display", // Custom CSS variable name
  subsets: ["latin"],
  weight: ["400", "700"], // Example: You can add weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${redHatDisplay.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />  
      </body>
    </html>
  );
}
